#plot of intron and exon length in human

data_lncRNA <- read.csv("lncrna_length_h.csv", header = T)
head(data_lncRNA)
data_CDS <- read.csv("mrna_length_h.csv", header = T)
head(data_CDS)
TPE <- c(data_lncRNA$TPE, data_CDS$TPE)
x <- median(TPE)

a <- data_lncRNA %>% filter(TPE <= x)
count(a)
b <- data_lncRNA %>% filter(TPE > x)
count(b)
a1 <- data_CDS %>% filter(TPE <= x)
count(a1)
b1 <- data_CDS %>% filter(TPE > x)
count(b1)
mean(a$intron_length)
mean(b$intron_length)
mean(a1$intron_length)
mean(b1$intron_length)
median(a$intron_length)
median(b$intron_length)
median(a1$intron_length)
median(b1$intron_length)
mean(a$exon_length)
mean(b$exon_length)
mean(a1$exon_length)
mean(b1$exon_length)
median(a$exon_length)
median(b$exon_length)
median(a1$exon_length)
median(b1$exon_length)
wilcox.test(a$intron_length, b$intron_length, alternative = "greater")
wilcox.test(a1$intron_length, b1$intron_length, alternative = "greater")
wilcox.test(a$exon_length, b$exon_length, alternative = "greater")
wilcox.test(a1$exon_length, b1$exon_length, alternative = "greater")

tiff("/home/dell/Documents/koushiki/final_fig/fig_2b3.tiff",width = 1200, height = 1200, res = 400)
par(mar=c(1,3,0.5,0.5))
boxplot(a$intron_length/1000000, b$intron_length/1000000, col = c("#31A2AC","#3A5199"), xlab="",xaxt='n', ylab="", boxwex=0.9,
        at=c(1,2), outline=F, xlim=c(0,6), ylim=c(0,0.4), main="", cex.axis=1.6, font.axix=2)
boxplot(a1$intron_length/1000000, b1$intron_length/1000000, add= TRUE,col = c("#EB8A3E","#CB0000"), boxwex=0.9, at=c(4,5), outline=F, axes=F)
box(col="black", lwd=2)
dev.off()

a <- data_lncRNA %>% filter(TPE <= x)
count(a)
b <- data_lncRNA %>% filter(TPE > x)
count(b)
a1 <- data_CDS %>% filter(TPE <= x)
count(a1)
b1 <- data_CDS %>% filter(TPE > x)
count(b1)

tiff("/home/dell/Documents/koushiki/final_fig/fig_2b4.tiff",width = 1200, height = 1200, res = 400)
par(mar=c(1.2,3,1.2,0.5))
boxplot(a$exon_length/1000000, b$exon_length/1000000, col = c("#31A2AC","#3A5199"), xlab="",xaxt='n', ylab="", boxwex=0.9,
        at=c(1,2), outline=F, xlim=c(0,6), ylim=c(0,0.03), main="", cex.axis=1.6, font.axix=2)
boxplot(a1$exon_length/1000000, b1$exon_length/1000000, add= TRUE,col = c("#EB8A3E","#CB0000"), boxwex=0.9, at=c(4,5), outline=F, axes=F)
box(col="black", lwd=2)
dev.off()